Added OK events
electioncal/us pull request #33
Opened 2020-06-25 17:02 UTC by askpatrickw

2020-06-25 17:37 UTC, tannewt requested changes
Thank you!

2020-06-25 17:37 UTC, tannewt commented on states/oklahoma/elections.toml
> +]
I think you want this section on the next two elections as well.

2020-06-26 05:14 UTC, askpatrickw commented
Review again based on this info.


Returning Your Ballot

If your absentee ballot is mailed to you, you must return it to the county election board by mail. An absentee ballot must be received by the county election board before 7 p.m. on election day to be counted. Standard absentee ballots may also be delivered in-person to your county election board during regular business hours. Ballots delivered by hand must be returned no later than the end of business hours on the day before the election. Only standard absentee ballots may be returned in-person, and the voter must show proper identification. Those who request absentee ballots under the special conditions listed below for those who are physically incapacitated or care for physically incapacitated persons who cannot be left alone may only return their ballots by mail.

In-person Absentee Voting

Voters may cast an absentee ballot in person at the county election board office from 8 a.m. to 6 p.m. on Thursday and Friday before all elections. For state and federal elections only, in-person absentee voting also is available from 9 a.m. to 2 p.m. on Saturday. In-person absentee voters must fill out and sign an application form when they arrive to vote.



Also.... if any events _should_ be there (you think) but there's no info... add them and comment them out.

2020-06-26 20:03 UTC, askpatrickw commented
Yep... I just totally missed adding those. Good catch, thank you !

2020-06-27 01:52 UTC, tannewt approved these changes
Thank you!

2020-06-27 01:52 UTC, merged