Add TN Events
electioncal/us pull request #60
Opened 2020-06-30 07:18 UTC by askpatrickw

Tennessee State Motto: Agriculture and Commerce

2020-06-30 07:21 UTC, askpatrickw commented
This isn't ready, but I can't put to Draft.
Missed .absentee ... twice. :-/

2020-06-30 07:21 UTC, askpatrickw commented
NVM, it changed to draft, the dialog just didn't go away when I clicked it.

2020-07-01 04:21 UTC, tannewt requested changes
Two typos. Dates look good!

2020-07-01 04:21 UTC, tannewt commented on states/tennessee/elections.toml
> +[20201103.asbsentee]
```suggestion
[20201103.absentee]
```

2020-07-01 04:21 UTC, tannewt commented on states/tennessee/elections.toml
> +[20200806.asbsentee]
```suggestion
[20200806.absentee]
```

2020-07-01 17:15 UTC, askpatrickw commented
Thanks @tannewt  !

2020-07-02 01:16 UTC, tannewt approved these changes
Thank you!

2020-07-02 01:16 UTC, merged