Add mn events
electioncal/us pull request #65
Opened 2020-07-03 01:14 UTC by askpatrickw

As I mentioned in Discord, Minnesota says...  

https://www.sos.state.mn.us/elections-voting/other-ways-to-vote/vote-early-by-mail/
> Application deadline
> You can apply for a ballot any time during the year, except the day of the election. Leave time for election officials to mail your ballot. Your returned ballot must be postmarked on or before Election Day (August 11, 2020) and received by your county by the day before the county canvass, which may take place on the second or third day following the election. 

I didn't see an actual date for received by for absentee though which to my eye means yeah you can legally mail it in 2 days before but you're not going to get a ballot and send it back in time.

We could leave it alone and just publish the rule or we could pad the date back X days.
I think we should just publish the rules. If you want to pad, I suggest 5 days.

I remember @tannewt  saying something about this before. If there's some rule you want to use for consistency just let me know.

Thanks!
Thanks!

2020-07-07 05:10 UTC, tannewt requested changes
One comment about the absentee application. I think we should account for mail delay in our dates.

2020-07-07 05:10 UTC, tannewt commented on states/minnesota/elections.toml
> +email_by =  2020-08-10 # Legally this is true, but you'll never receive it.
I think I'd do two or three weeks on this. 1 to send in, 1 to get ballot and 1 to send ballot. Only received_by will be reminded a week out so maybe ~2 for all and received_by will be offset further.

2020-07-08 04:39 UTC, askpatrickw commented
I'm going to email MN and see why they think these days can be so close. Maybe I'm not understanding... for example, maybe you email it and then go pick it up.. 🤷

2020-07-14 15:58 UTC, tannewt commented
I think RI actually states they'll drive the ballot out to you. So, that is possible as well.

2020-07-14 23:41 UTC, askpatrickw commented
I padded the dates by 14 days since we've had no reply. Will resubmit for review when CI passes.

2020-07-15 03:26 UTC, tannewt approved these changes
Thank you!

2020-07-15 03:26 UTC, merged