Add ct events
electioncal/us pull request #66
Opened 2020-07-04 21:23 UTC by askpatrickw

On hold: Looking for absentee.aplicaiton deadlines...

2020-07-06 06:25 UTC, askpatrickw commented
I thought fresh eyes would help... nope can't find it. I emailed the CT Elections Commission.

2020-07-06 06:32 UTC, askpatrickw commented
Wow... Multiple email addresses listed on the CT site are bouncing...

2020-07-07 05:16 UTC, tannewt commented
> On hold: Looking for absentee.application deadlines...

Maybe go by `Absentee ballots are to be provided by the municipal clerk beginning 31 days before an election, 21 days before a primary, or 19 days before a referendum, upon application properly made.`?

It's not super urgent since absentee is limited still.

2020-07-07 17:31 UTC, askpatrickw commented
August 10 for both is the answer:

> From: SOTS LEAD <LEAD@ct.gov>
> Sent: Tuesday, July 7, 2020 10:13 AM
> To: Patrick Walters
> Subject: RE: Absentee Application Deadlines
> 
> yes
> 
> Legislation & Elections Administration Division
> Secretary of the State Office
> (860) 509-6271
> 
> -----Original Message-----
> From: Patrick Walters <patrickwalters@outlook.com>
> Sent: Tuesday, July 7, 2020 1:12 PM
> To: SOTS LEAD <LEAD@ct.gov>
> Subject: Re: Absentee Application Deadlines
> 
> Thank you,
> 
> And the date for the General Election on Nov 3rd?
> 
> 
> Thanks,
> Patrick
> 
> ________________________________________
> From: SOTS LEAD <LEAD@ct.gov>
> Sent: Tuesday, July 7, 2020 10:10 AM
> To: Patrick Walters
> Subject: RE: Absentee Application Deadlines
> 
> It is August 10.
> 
> 
> Legislation & Elections Administration Division Secretary of the State Office
> (860) 509-6271
> 
> -----Original Message-----
> From: Patrick Walters <patrickwalters@outlook.com>
> Sent: Tuesday, July 7, 2020 1:09 PM
> To: SOTS LEAD <LEAD@ct.gov>
> Subject: Fw: Absentee Application Deadlines
> 
> Hello,
> 
> I have a Connecticut election deadline question.
> 
> I know that when voting absentee, your completed ballot must be received by 8pm on the election day. But, what is the deadline to submit an absentee ballot application for both the August 11 Primary and the November 3rd General Election?

2020-07-09 15:29 UTC, tannewt requested changes

2020-07-09 15:29 UTC, tannewt commented on states/connecticut/elections.toml
> +on_line_by = 2020-08-06
```suggestion
online_by = 2020-08-06
```

2020-07-09 15:29 UTC, tannewt commented on states/connecticut/elections.toml
> +on_line_by = 2020-08-06
I believe we've used the single underscore version before.

2020-07-10 04:03 UTC, tannewt approved these changes
Looks good! Thank you!

2020-07-10 04:03 UTC, merged