Alaska
electioncal/us pull request #75
Opened 2020-07-10 05:48 UTC by askpatrickw

Alaska State Motto: "North to the Future"

2020-07-10 06:31 UTC, tannewt requested changes
Found received_by deadline which is 10 days after election. Shouldn't trigger a reminder but still nice to have.

2020-07-10 06:31 UTC, tannewt commented on states/alaska/elections.toml
> +postmarked_by = 2020-11-03
2020-11-13 received_by date:

> 11/13/2020 | Deadline to receive absetee ballots mailed from **within the U.S.**, U.S.  territories of Puerto Rico, Guam, the Virgin Islands, American Samoa.`

2020-07-10 06:31 UTC, tannewt commented on states/alaska/elections.toml
> +postmarked_by = 2020-08-18
received_by 2020-08-28

2020-07-10 21:00 UTC, askpatrickw commented
Added the absentee received_by dates

2020-07-12 03:19 UTC, tannewt approved these changes
Thank you!

2020-07-12 03:19 UTC, merged