TX General Election Dates
electioncal/us pull request #89
Opened 2020-07-26 00:00 UTC by askpatrickw

2020-07-26 00:13 UTC, askpatrickw commented
TX is sooooo big it takes 2 PRs. ;-)

2020-07-27 01:12 UTC, tannewt requested changes
One copy and paste issue. Good otherwise!

2020-07-27 01:12 UTC, tannewt commented on states/texas/elections.toml
> +in_person_start = 2020-11-19
```suggestion
in_person_start = 2020-10-19
```

2020-07-27 02:43 UTC, askpatrickw commented on states/texas/elections.toml
> +in_person_start = 2020-11-19
Thanks @tannewt  All done.

2020-07-27 02:44 UTC, tannewt approved these changes
Thank you!

2020-07-27 18:55 UTC, merged